### PR TITLE
Add drag and lift

### PR DESCRIPTION
**Pull request by ericman314**

### CODE REVIEW

**Comment by donrodriguez** [comment]
I’m working on the drag coefficient and area. What’s the height and diameter of the rocket you used?

**Comment by ericman314** [comment]
The parameters I used are defined in simulation.py [here](https://github.com/ericman314/dynamic-optimization/blob/6a940bae313c026cd7329544e5154ec1d856f4d0/rocket/simulation.py#L67-L76) and [here](https://github.com/ericman314/dynamic-optimization/blob/6a940bae313c026cd7329544e5154ec1d856f4d0/rocket/simulation.py#L272-L276). I don't they are very accurate, especially, I think the drag increases way too fast with increasing angle of attack. I basically used the cross section of the rocket in the airflow with the same drag coefficient all the way through, but I don't know if that was the right way to do it. If you can improve it would be great, but eventually we'll just need freeze simulation.py as is and start training the model. Any changes after that point would require us to retrain the model.

**Comment by donrodriguez** [comment]
Okay, thanks.

I’m really sorry that I’ve been dead weight these past 2 weeks. I absolutely hate being useless. 

I’ll try to improve the drag coefficient.

Are we using NN to train our model, then?

We plan on submitting this tomorrow night, right? Do we have a google doc set up?

**Comment by ericman314** [comment]
Yeah let's continue that conversation on Slack

**Pull request merged**
